source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JMMaterialTableView_Example', :exclusive => true do
  pod "JMMaterialTableView", :path => "../"
end

target 'JMMaterialTableView_Tests', :exclusive => true do
  pod "JMMaterialTableView", :path => "../"

  
end
